student_work_homepage:
    path:     /hello/{name}
    defaults: { _controller: StudentWorkBundle:Default:index }
    
home:
    path: /
    defaults: { _controller: StudentWorkBundle:Work:index }
    
login:
    path: /login
    defaults: { _controller: StudentWorkBundle:Work:login }
    
logout:
    path: /logout
    defaults: { _controller: StudentWorkBundle:Work:logout }
